### ISSUE TITLE
OPA Gatekeeper should be updated to support Kubernetes 1.22

### ISSUE THREAD

**Issue by giannisalinetti** [killer-sh/cks-course-environment#11]
The current OPA Gatekeeper deploy file uses API objects that are removed in Kubernetes 1.22, specifically apiextensions.k8s.io/v1beta1. Updating the name of the API obgject to apiextensions.k8s.io/v1 is not enough since the schema has changed.

The workaround to continue the course was using the official latest release:
https://raw.githubusercontent.com/open-policy-agent/gatekeeper/v3.5.2/deploy/gatekeeper.yaml

The course YAML should be updated accordingly.

**Comment by wuestkamp** [comment]
Thanks @giannisalinetti
We'll look into it once we update to 1.22
