### ISSUE TITLE
Worker script failing with Ubuntu 20.04 Focal Fossa LTS when package were held

### ISSUE THREAD

**Issue by quercusilvam** [killer-sh/cks-course-environment#16]
Hi,

I found little issue with the worker script (https://github.com/killer-sh/cks-course-environment/blob/master/cluster-setup/latest/install_worker.sh).
If packages were installed before and held the script failed.

As improvement script should remove held packages or stop and print some error msg; currently it continues and fail in later stage

LOG:
The following packages will be REMOVED:
  kubeadm kubectl kubelet kubernetes-cni
The following held packages will be changed:
  kubeadm
0 upgraded, 0 newly installed, 4 to remove and 34 not upgraded.
E: Held packages were changed and -y was used without --allow-change-held-packages.

BR, Silvam

**Comment by wuestkamp** [comment]
Thanks @quercusilvam
