### ISSUE TITLE
Missing etcd-client package from the cluster scripts

### ISSUE THREAD

**Issue by fabricev** [killer-sh/cks-course-environment#22]
Hello,

The etcd client package on ubuntu could be added in the master setup scripts, for convenience (section 76).
```
apt-get install etcd-client
```
Regards,
Fabrice.

PS: added later manually on in section 78, however. Feel free to archive.

**Comment by wuestkamp** [comment]
Thanks @fabricev
There can actually be version issues between the api etcd-client package and the kubeadm etcd version running, so best to install specific version
