### ISSUE TITLE
The instrumenta/conftest image is deprecated and will no longer be updated.

### ISSUE THREAD

**Issue by oke-py** [killer-sh/cks-course-environment#4]
In the lectures 115 and 116, `instrumenta/conftest` image is used, but it is deprecated.

> NOTE: The instrumenta/conftest image is deprecated and will no longer be updated. Please use the openpolicyagent/conftest image.

https://github.com/open-policy-agent/conftest/blob/master/docs/install.md#docker

**Comment by wuestkamp** [comment]
thanks for reporting @oke-py ! :)
