### ISSUE TITLE
kubernetes repository address need update

### ISSUE THREAD

**Issue by haikal00** [killer-sh/cks-course-environment#61]
Hi,
https://github.com/killer-sh/cks-course-environment/blob/master/cluster-setup/latest/install_master.sh#L68
This line in cluster setup script need update following a blog post here 
https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

**Comment by wuestkamp** [comment]
Thanks a lot @haikal00 !
Updated the install scripts
