### ISSUE TITLE
Falco docs link out of date

### ISSUE THREAD

**Issue by joelvdvoort** [killer-sh/cks-course-environment#70]
Hello,

In the resource section the link to the Falco docs is outdated and no longer working.

File: https://github.com/killer-sh/cks-course-environment/blob/master/Resources.md
Relevant link: https://v1-16.docs.kubernetes.io/docs/tasks/debug-application-cluster/falco

Thank you very much for the course by the way. It's pretty good!

**Comment by wuestkamp** [comment]
Thanks @joelvdvoort fixed in https://github.com/killer-sh/cks-course-environment/pull/72
