### ISSUE TITLE
Question 12 solution is not working

### ISSUE THREAD

**Issue by j-karls** [killer-sh/cks-course-environment#81]
Hi
It appears to me that question 12 (Hack Secrets) is not working as intended. 
I am not able to get pods when within the correct context, which means that I cannot solve the question in any way. 
![image](https://github.com/user-attachments/assets/8a36ed83-2730-4563-9682-c8b5473fa1d9)

**Comment by wuestkamp** [comment]
For questions about the simulators ask in https://killer.sh/slack or create a ticket on https://killer.sh/support.
In this case checking the provided simulator solution should show how to tackle this question.
This question provides a kubectl context with few permissions on purpose.

**Comment by j-karls** [comment]
The provided solution does not work. It requires that one uses kubectl get pods, which is not possible, as mentioned in my initial issue. As you can see, k get pod is not an allowed command. 

![image](https://github.com/user-attachments/assets/2bc84fde-9718-4ad5-8e94-25d5bc7db0d7)
